dev:
  BASE_URL: https://jsonplaceholder.typicode.com
  TIMEOUT: 10

staging:
  BASE_URL: https://jsonplaceholder.typicode.com
  TIMEOUT: 15

prod:
  BASE_URL: https://jsonplaceholder.typicode.com
  TIMEOUT: 20
